#install: make get-deps
#./configure && make && make test

language: c
compiler: 
    - clang
    - gcc
before_script:
        - cd "codigo fonte"
        - ls
        - pwd
script: 
        - pwd
        - make
        
